### ISSUE TITLE
Реализовать более сложную логику сравнения объектов

### ISSUE THREAD

**Issue by AlphaBeth** [dmittrey/PROG#4]
Задействовать несколько полей, которые вводятся пользователем, автоматически сгенерированные можно использовать, но в последнюю очередь (если по всем остальным полям объекты оказались равны).

**Comment by dmittrey** [comment]
Реализовал сравнение по трём полям:
1) Кол-во студентов
2) Средняя оценка(проверил на null)
3) Дата создания(При прочих равных побеждает самый новый объект)

Коммит Compare issue

**Comment by AlphaBeth** [comment]
Повторяются одни и те же вычисления. Если вдруг решите поменять логику, нужно будет не забыть поменять её в двух местах. Вынести в переменную промежуточный результат - нужно будет менять только одно место.
https://github.com/dmittrey/PROG/blob/13fbed7dfa24d458d09056b26b84cebd298fc102/Lab5/src/data/StudyGroup.java#L169-L172
