### ISSUE TITLE
По-хорошему, команды должны возвращать не строки, а объект

### ISSUE THREAD

**Issue by AlphaBeth** [dmittrey/PROG#5]
Объект содержит информацию об ответе: это может быть и строка, и коллекция каких-то элементов, и что-то ещё.

Можете сейчас не переделывать, но вам всё равно придётся это сделать в следующей лабе.

**Comment by dmittrey** [comment]
Я немного не понимаю пока что как я буду организовывать работу клиент-сервер в 6 лабораторной, но я поменял возвращаемое значение в интерфейсе, абстрактном классе и всех его расширяющих классах и написал что мы можем в теории вернуть кроме строки. (Извините если это бред)

Изменения в коммите "String issue"
